allprojects {
    repositories {
        google()
        mavenCentral()
    }
}

rootProject.buildDir = "../build"
subprojects {
    project.buildDir = "${rootProject.buildDir}/${project.name}"
}
subprojects {
    project.evaluationDependsOn(":app")
}

subprojects {
    pluginManager.withPlugin('com.android.library') {
        if (project.hasProperty('android')) {
            if (project.android.namespace == null) {
                if (project.name == 'telephony') {
                    project.android.namespace = 'com.shounakmulay.telephony'
                } else {
                    project.android.namespace = "com.example.${project.name.replace('-', '_')}"
                }
            }
        }
    }
}

tasks.register("clean", Delete) {
    delete rootProject.buildDir
}
